Javascript: Library v1.1
diazgio/Library-JS pull request #1
Opened 2021-01-21 17:13 UTC by mke2111

# Library v1.1

**In this project, we implemented a simple library store using vanilla Javascript with the given functionality.**

- Add a new Book.
- Delete an existing book.
- Change the read status of a book.
- Books are stored in the local storage of the browser.

2021-01-21 18:13 UTC, addod19 requested changes
## Status: Require changes :recycle: :traffic_light: 

Hi @mke2111 and @diazgio, great job on this project :+1: The project works as expected and has all the features of the app :smile: However, there a few comments we need to address before proceeding :slightly_smiling_face: Kindly check the comments below:

- The index file should have 1 element, for example `<div id="root"></div>` where all the other elements are appended to the parent node. It would be great to create a file for the DOM manipulation task
- The screenshot in the README is broken, kindly fix it
- Kindly add instructions about how to run the app locally
- Kindly implement the ES6 arrow function, for example; replace `function name(){}` with `const name = () => {}`
- Kindly implement a modal for our alert messages instead of the `alert()` or `confirm()`


[Optional]
- Kindy fix the input for the number of pages.  The input type for the number of pages should be `type="number"`

Once these are addressed, kindly submit another code review request :smile: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](linkedin.com/in/daniel-larbi-addo/)

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function showForm() {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function updateLocalStorage() {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function addNewBooks() {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function readContent(s) {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function showBooks() {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function getLocalStorage() {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function deleteBook(book) {
An ES6 arrow function can be implemented here

2021-01-21 18:13 UTC, addod19 commented on src/JS/app.js
> +function readStatus(s) {
An ES6 arrow function can be implemented here

2021-01-22 22:49 UTC, diazgio commented
We try to change the UNIQUE issue with the ESlint that we have but crash the entire app, so we decide to keep that line it's the only thing that is missing, we manage to make all the changes that were requested.

2021-01-23 02:58 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 

Great job guys, thanks for making the required changes.

now you can merge, but please first add this disable line before the import that is causing the linter error: `/* eslint-disable import/extensions */`

## Happy Coding :tophat:

2021-01-23 09:17 UTC, merged